name: WakaTime Stats Update

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours to update work time
  workflow_dispatch:  # Allows manual updates

jobs:
  update-readme:
    name: Update WakaTime Readme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
